version: '3.9'

services:
  delivery_user_service:
    build: ../../user-service/.
    container_name: delivery_user_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://delivery_user_db:5432/delivery-auth
      - RABBITMQ_HOST=delivery_rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - delivery_user_db
      - delivery_rabbitmq

  delivery_confirmation_service:
    build: ../../confirmation-service
    container_name: delivery_confirmation_service
    environment:
      - RABBITMQ_HOST=delivery_rabbitmq
      - SMTP_HOST=delivery_mailhog
      - SMTP_PORT=1025
    ports:
      - "8083:8083"
    depends_on:
      - delivery_mailhog
      - delivery_rabbitmq

  delivery_order_service:
    build: ../../order-service/.
    container_name: delivery_order_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://delivery_order_db:5432/delivery-order
      - RABBITMQ_HOST=delivery_rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      - delivery_order_db
      - delivery_rabbitmq

  delivery_tracking_service:
    build: ../../tracking-service/.
    container_name: delivery_tracking_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://delivery_tracking_db:5432/delivery-tracking
      - RABBITMQ_HOST=delivery_rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      - delivery_tracking_db
      - delivery_rabbitmq

  delivery_mailhog:
    image: mailhog/mailhog
    container_name: delivery_mailhog
    ports:
      - "2025:1025"
      - "9025:8025"

  delivery_user_db:
    image: postgres:latest
    container_name: delivery_user
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=delivery-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=delivery-auth

  delivery_order_db:
    image: postgres:latest
    container_name: delivery_order_db
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_USER=delivery-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=delivery-order

  delivery_tracking_db:
    image: postgis/postgis:latest
    container_name: delivery_tracking_db
    ports:
      - "6434:5432"
    environment:
      - POSTGRES_USER=delivery-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=delivery-tracking
      - POSTGIS_EXTENSION=postgis

  delivery_rabbitmq:
    image: rabbitmq:3-management
    container_name: delivery-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


